Add methods for creating a dir, getting current dir, create a new fil…
yairdar/ydu-202-searchapp pull request #5
Opened 2022-04-24 16:25 UTC by VitaliyKrivoshchapov

…e, get list of  all nested dir

2022-04-26 16:22 UTC, yairdardev requested changes
please add tests for API 
- /collections/set_item/
- /collections/get_item/
- /collections/list
see #4

2022-04-26 16:22 UTC, yairdardev commented on searchup/blocks/djfedos_db/test_CollectionsManager.py
> +    from fastapi.testclient import TestClient
not in use remove

2022-04-26 16:22 UTC, yairdardev commented on searchup/blocks/djfedos_db/test_web_server_tokens.py
> +# add get
@VitaliyKrivoshchapov 
its good you have added tests for implementation, 
but you need to add Please add Tests for API,

using TestClient

see examples in this file
```
 client = TestClient(app)
response = client.get("/get_suggestions/" + prefix)
```

you need to test next endpoints:
```python
@app.post("/collections/set_item/{item_name_id}")
def set_collection_item(item_name_id):
  ...

@app.get("/collections/get_item/{item_name_id}")
def get_collection_item(item_name_id):
   ...

@app.get("/collections/list")
def list_collections(prefix):
   ...
```

2022-04-26 18:12 UTC, yairdardev commented on searchup/blocks/djfedos_db/CollectionsManager.py
> +            return p
p.name

2022-04-26 18:40 UTC, yairdardev commented on searchup/blocks/djfedos_db/CollectionsManager.py
> +        #(p / f"{kind}.txt").write_text("")
return p.name

2022-04-26 18:40 UTC, yairdardev commented on searchup/blocks/djfedos_db/CollectionsManager.py
> +    # print("print tmpdir", tmpdir)
remove comments

2022-04-26 18:41 UTC, yairdardev commented
@lioryah

2022-05-03 08:07 UTC, djfedos commented on searchup/blocks/djfedos_db/CollectionsManager.py
> +            return p
fixed, thanks!

2022-05-03 08:07 UTC, djfedos commented on searchup/blocks/djfedos_db/CollectionsManager.py
> +        #(p / f"{kind}.txt").write_text("")
fixed, thanks!

2022-05-03 08:07 UTC, djfedos commented on searchup/blocks/djfedos_db/CollectionsManager.py
> +    # print("print tmpdir", tmpdir)
fixed, thanks!

2022-05-03 08:10 UTC, djfedos commented on searchup/blocks/djfedos_db/test_CollectionsManager.py
> +    from fastapi.testclient import TestClient
removed, thanks!

2022-05-13 10:06 UTC, djfedos requested changes

2022-05-13 10:06 UTC, djfedos commented on searchup/blocks/djfedos_db/fapi_server.py
> +# create a new director
this is already in CollectionManager, remove lines 170 to 190

2022-05-13 10:06 UTC, djfedos commented on searchup/blocks/vit_db/creat_db.py
> +
Please remove all the PostgreSQL related code from this branch

2022-06-16 11:10 UTC, yairdardev commented
@VitaliyKrivoshchapov please close it or fix and merge

2022-06-19 12:37 UTC, closed without merging